[package]
name = "qtictactoe"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.17", features = ["derive"] }
rand = "0.8.5"
rustc-hash = "1.1.0"

[profile.release]
lto = true
